### ISSUE TITLE
Ability to request a worker to only run jobs from a specific queue

### ISSUE THREAD

**Issue by robacarp** [mosquito-cr/mosquito#2]
I should be able to do something like this:

```crystal
Mosquito::Runner.new queue_whitelist: /-image-processing/
```

**Comment by Blacksmoke16** [comment]
Bump.  This would be great for what I'm trying to do.  I would like to have a worker process that runs periodic jobs, then another for normal async jobs.  This would allow you to scale the number of async consumers without affecting the periodic jobs.  

I was thinking I could do this by only requiring the related jobs in each worker file, but this breaks down when I wanted to enqueue the async jobs from within the periodic job.

**Comment by emanzx** [comment]
+1 for me. I would love to have this features too as I need specific worker that I place on specific region to access only specific queue and specific queue for specific worker.
